name: Test Build

on:
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: build (${{ matrix.channel }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - channel: current
            node: node
          - channel: lts
            node: lts/*
          - channel: lts-maintenance
            node: lts/-1

    steps:
      - uses: actions/checkout@v5

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install
        run: npm ci

      - name: Build
        env:
          CI: true
        run: npm run build

  gate:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Report
        run: |
          if [ "${{ needs.build.result }}" = "success" ]; then
            echo "✅ Build success"
          else
            echo "❌ Build failed"; exit 1
          fi
